site_name: Ashkin's Notes
site_url: https://github.com/AshkinLi/notes
site_author: Ashkin Y C Li
site_description: >-
  Ashkin's Notes

repo_name: 

theme:
  name: material

nav:
  - Bookmarks: index.md
