# Project information
site_name: Ashkin's Notes
site_url: https://github.com/AshkinLi/notes
site_author: Ashkin Y C Li
site_description: >-
  Ashkin's Notes

# Repository
repo_name: AshkinLi/notes
repo_url: https://github.com/AshkinLi/notes
edit_uri: blob/source/docs/

# Configuration
theme:
  name: material
  logo: assets/logo.jpeg
  language: zh
  favicon: assets/logo.jpeg
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  icon: 
    repo: fontawesome/brands/github
  palette:
    primary: light blue
    accent: light blue

# Plugins
plugins:
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated

  generator: false

# Extensions
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Bookmarks: index.md
  - Blogs:
    - blog/index.md
